apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: sre-machine-api-status-exporter
  namespace: openshift-monitoring
  labels:
    name: sre-machine-api-status-exporter
spec:
  replicas: 1
  selector:
    name: sre-machine-api-status-exporter
  template:
    metadata:
      name: sre-machine-api-status-exporter
      labels:
        name: sre-machine-api-status-exporter
    spec:
      containers:
      - name: "main"
        command: [ "/bin/sh", "/monitor/start.sh" ]
        workingDir: /monitor
        ports:
        - containerPort: 8080
          protocol: "TCP"
        image: quay.io/openshift-sre/managed-prometheus-exporter-base:0.1.3-5a0899dd
        env:
        - name: MACHINE_NAMESPACE
          value: openshift-machine-api
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 420
          periodSeconds: 360
          timeoutSeconds: 240
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 240
        volumeMounts:
        - name: monitor-volume
          mountPath: /monitor
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: sre-machine-api-status-exporter
      volumes:
      - name: monitor-volume
        configMap:
          name: sre-machine-api-status-exporter-code
  triggers:
  - type: ConfigChange
  strategy:
    type: "Recreate"
  paused: false
