apiVersion: v1
kind: Service
metadata:
  labels:
    name: sre-machine-api-status-exporter
  name: sre-machine-api-status-exporter
  namespace: openshift-monitoring
spec:
  ports:
  - name: http-main
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: sre-machine-api-status-exporter
  sessionAffinity: None
  type: ClusterIP
